### ISSUE TITLE
Use $HOME/.local/bin

### ISSUE THREAD

**Issue by stfnx** [tmuntaner/wsl-gpg-agent#176]
Hi,
maybe you want to consider using `$HOME/.local/bin` instead of `$HOME/bin` to store user-specific executables.
As described in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by tmuntaner** [comment]
Hi @stfnx,

you're totally right there. I opened #188 to fix it.
